// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc8gXyzqm8FyiVmSkI5Dt4JFV_nhAlDf4',
    appId: '1:236897926163:web:9a668004c8de0a1141d3e6',
    messagingSenderId: '236897926163',
    projectId: 'rvsapp-1',
    authDomain: 'rvsapp-1.firebaseapp.com',
    storageBucket: 'rvsapp-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB_wCsI5gpnq8-VuB0UtrBLTU_qpKTF-o',
    appId: '1:236897926163:android:2b25a2394c94f20841d3e6',
    messagingSenderId: '236897926163',
    projectId: 'rvsapp-1',
    storageBucket: 'rvsapp-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMptx9GVS9keVFkcvUjY7b7UCSP5W52lU',
    appId: '1:236897926163:ios:e39c66ada5f7246941d3e6',
    messagingSenderId: '236897926163',
    projectId: 'rvsapp-1',
    storageBucket: 'rvsapp-1.appspot.com',
    iosClientId: '236897926163-jf7vpdta8m8oumceevo4mrs7e0gdvhm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.rvs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMptx9GVS9keVFkcvUjY7b7UCSP5W52lU',
    appId: '1:236897926163:ios:e39c66ada5f7246941d3e6',
    messagingSenderId: '236897926163',
    projectId: 'rvsapp-1',
    storageBucket: 'rvsapp-1.appspot.com',
    iosClientId: '236897926163-jf7vpdta8m8oumceevo4mrs7e0gdvhm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.rvs',
  );
}
